# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('maiden_name', models.CharField(blank=True, max_length=50)),
                ('birth_city', models.CharField(blank=True, max_length=75)),
                ('birth_country', models.CharField(blank=True, max_length=75)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('profile_pic', models.ImageField(default='profile_folder/None/no-img.jpg', upload_to='profile_folder/')),
            ],
        ),
    ]
